name: Deploy to Maven Central and Gradle Plugin Portal

on:
  release:
    types: [released]
  pull_request:
    branches:
      - '**'

jobs:
  deploy:
    if: ${{ github.event_name == 'release' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Make Maven wrapper executable
        run: chmod +x ./mvnw
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '8'
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
          gpg-passphrase: SIGN_KEY_PASS
      - name: Build with Maven
        run: ./mvnw -B clean install
      - name: Publish Maven plugin
        run: ./mvnw -B deploy -pl slf4j-caller-info-maven -Dgpg.keyname=${{ secrets.MAVEN_GPG_PRIVATE_KEY }} -Dgpg.passphrase=${{ secrets.MAVEN_GPG_PASSPHRASE }} -Pci-cd
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
          SIGN_KEY_PASS: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
      - name: Make Gradle wrapper executable
        working-directory: ./slf4j-caller-info-gradle
        run: chmod +x ./gradlew
      - name: Publish Gradle plugin
        working-directory: ./slf4j-caller-info-gradle
        run: ./gradlew publishPlugins --no-daemon
        env:
          GRADLE_PUBLISH_KEY: ${{ secrets.GRADLE_PUBLISH_KEY }}
          GRADLE_PUBLISH_SECRET: ${{ secrets.GRADLE_PUBLISH_SECRET }}
